import SwiftUI

enum RoutineTypography {
    static let screenTitle = Font.system(size: 32, weight: .semibold)
    static let funnelTitle = Font.system(size: 25, weight: .semibold)
    static let funnelHeadline = Font.system(size: 24, weight: .bold)
    static let funnelWelcome = Font.system(size: 31, weight: .semibold)
    static let funnelBody = Font.system(size: 17, weight: .regular)
    static let funnelBodyMedium = Font.system(size: 17, weight: .medium)
    static let funnelSubtitle = Font.system(size: 16, weight: .regular)
    static let funnelSubtitleMedium = Font.system(size: 16, weight: .medium)
    static let funnelCaption = Font.system(size: 13, weight: .regular)
    static let funnelButton = Font.system(size: 17, weight: .semibold)
    static let compactTitle = Font.system(size: 23, weight: .semibold)
    static let sectionTitle = Font.system(size: 20, weight: .semibold)
    static let body = Font.system(size: 17, weight: .regular)
    static let bodyMedium = Font.system(size: 17, weight: .medium)
    static let secondary = Font.system(size: 15, weight: .regular)
    static let small = Font.system(size: 13, weight: .medium)
    static let smallRegular = Font.system(size: 13, weight: .regular)
    static let button = Font.system(size: 17, weight: .semibold)
    static let appName = Font.system(size: 18, weight: .medium)
    static let price = Font.system(size: 17, weight: .regular)
    static let timelineTitle = Font.system(size: 17, weight: .semibold)
    static let metric = Font.system(size: 26, weight: .semibold)
    static let chartLabel = Font.system(size: 11, weight: .regular)
    static let settingsTitle = Font.system(size: 26, weight: .bold)
    static let settingsRow = Font.system(size: 16, weight: .regular)
}
