#!/usr/bin/env bash
set -euo pipefail

name=""
bundle_id=""
team_id=""
revenuecat_key=""
revenuecat_app_store_key=""
revenuecat_entitlement="premium"
auth_enabled="NO"

usage() {
  cat <<'EOF'
Configure a local Routine starter clone.

Usage:
  ./scripts/bootstrap.sh --name "My App" --bundle-id com.example.myapp [--team-id TEAMID] [--enable-auth] [--revenuecat-key TEST_KEY] [--revenuecat-app-store-key APPLE_KEY] [--revenuecat-entitlement premium]

Writes apps/mobile/Config/Local.xcconfig. This file is ignored by Git.
EOF
}

while [[ $# -gt 0 ]]; do
  case "$1" in
    --name) name="${2:-}"; shift 2 ;;
    --bundle-id) bundle_id="${2:-}"; shift 2 ;;
    --team-id) team_id="${2:-}"; shift 2 ;;
    --enable-auth) auth_enabled="YES"; shift ;;
    --revenuecat-key) revenuecat_key="${2:-}"; shift 2 ;;
    --revenuecat-app-store-key) revenuecat_app_store_key="${2:-}"; shift 2 ;;
    --revenuecat-entitlement) revenuecat_entitlement="${2:-}"; shift 2 ;;
    -h|--help) usage; exit 0 ;;
    *) echo "Unknown argument: $1" >&2; usage; exit 1 ;;
  esac
done

[[ -n "$name" ]] || { echo "--name is required" >&2; exit 1; }
[[ "$bundle_id" =~ ^[A-Za-z0-9-]+(\.[A-Za-z0-9-]+)+$ ]] || {
  echo "--bundle-id must look like com.example.app" >&2
  exit 1
}

mkdir -p apps/mobile/Config
cat > apps/mobile/Config/Local.xcconfig <<EOF
// Generated by scripts/bootstrap.sh
APP_DISPLAY_NAME = $name
APP_BUNDLE_ID = $bundle_id
APP_TEST_BUNDLE_ID = $bundle_id.tests
APP_UI_TEST_BUNDLE_ID = $bundle_id.uitests
DEVELOPMENT_TEAM_ID = $team_id
AUTH_ENABLED = $auth_enabled
REVENUECAT_API_KEY = $revenuecat_key
REVENUECAT_APP_STORE_API_KEY = $revenuecat_app_store_key
REVENUECAT_ENTITLEMENT_ID = $revenuecat_entitlement
EOF

echo "Wrote apps/mobile/Config/Local.xcconfig"
echo "Open apps/mobile/RoutineApp.xcodeproj or run ./scripts/run-app.sh"
